Выполняет разметку главной страницы
htmlacademy-htmlcss/779351-nerds-31 pull request #2
Opened 2021-05-26 21:58 UTC by kafka2020

2021-05-26 22:54 UTC, wrgraff requested changes
Ну в общем неплохая работа!
И мне нравится, что лишнего нет )

Немного о том, как я ревью делаю.
Важные моменты, на которые нужно обязательно обратить внимание, я отмечаю смайлом ракеты `🚀`. То, что в правках не нуждается, отмечено смайлом `👍`. Некоторые комментарии без отметок. Если не понимаешь их или не успеваешь, то можно их оставить до следующей консультации или же вообще пропустить.
Еще прошу не нажимать на кнопку "Resolve conversation". Мне потом неудобно смотреть что я там написал. Пускай это будет моя кнопка =) Я буду ее жать если проблема исправлена. Ты можешь для себя тоже отмечать исправленный комментарий каким-то эмодзи, или писать комментарий в ответ. Как захочешь.

2021-05-26 22:54 UTC, wrgraff commented on index.html
> +          <img src="" alt="Логотип" width="" height="">
Логотип какой? Добавь чуть понятнее `alt`.
`width` и `height` можешь заполнить, раз уж написал )

2021-05-26 22:54 UTC, wrgraff commented on index.html
> +          <li><a href="#">Студия</a></li>
Если тег вложен, то лучше бы писать его на отдельной строке

2021-05-26 22:54 UTC, wrgraff commented on index.html
> +        <a href="#">УЗНАТЬ БОЛЬШЕ</a>
Старайся писать не капсом.
Капс лучше через стили включать

2021-05-26 22:54 UTC, wrgraff commented on index.html
> +      <section>
Секции хорошо бы добавить заголовок. Всем секциям нужен заголовок )
Если не придумать заголовок секции, то может это и не секция вовсе...

2021-05-26 22:54 UTC, wrgraff commented on index.html
> +      </section>
Там 3 слайда. Посмотри в макете.
3 слайда и кнопки для управления ими

2021-05-26 22:54 UTC, wrgraff commented on index.html
> +            <img src="" alt="">
Подходит ли эта картинка на роль контентной?

2021-05-26 22:54 UTC, wrgraff commented on index.html
> +      </section>
Неплохо разметил

2021-05-26 22:54 UTC, wrgraff commented on index.html
> +          <li><img src="" alt="MISHKA"></li>
А почему ссылка только на один есть? )
У нас только одна известная ссылка, а остальные неизвестны, но тоже есть )

2021-05-26 22:54 UTC, wrgraff commented on index.html
> +          наб. Реки Карповки,<br>
Давай договоримся пока не использовать `<br>`.
Дело в том, что форматированный текст вести себя будет иначе, а нам на этапе сеток нужно будет убедиться, что он подстраивается под сетку вне зависимости от форматирования.
Мы потом сможем поставить переносы, если это будет нужно.

2021-05-26 22:54 UTC, wrgraff commented on index.html
> +        <button type="button">Напишите нам</button>
А если js не будет работать, можно ли как-то предусмотреть возможность заполнить форму?

2021-05-27 05:37 UTC, kafka2020 commented on index.html
> +          <img src="" alt="Логотип" width="" height="">
Я заметил, что пропустил, но решил оставить так - проверял - заметишь или нет :)

2021-05-27 07:01 UTC, kafka2020 commented on index.html
> +      </section>
Пока не очень знаю как их верстать. Думал, потом сделаем. Попытаюсь исправить

2021-05-27 07:13 UTC, kafka2020 commented on index.html
> +            <img src="" alt="">
Фоновой через CSS добавим?

2021-05-27 07:16 UTC, kafka2020 commented on index.html
> +      </section>
А почему здесь нужен тег <img> для логотипа? Он не контентный тут тоже

2021-05-27 12:58 UTC, wrgraff commented on index.html
> +          <img src="" alt="Логотип" width="" height="">
Ага, я запомнил.
Тоже тебя проверю как-нибудь. На защите как получишь 2% за попытку первую, будешь знать )

2021-05-27 13:03 UTC, wrgraff commented on index.html
> +      </div>
С разметкой все хорошо, но семантики как-то маловато.
В принципе, можно же как-то это обозвать и объединить в `<section>`.
Вот ты меня проверял, а я тебя ) Поведешься ты на ложный намек убрать секцию или нет )

Слайды в список иногда объединяют. А иногда нет.
Тут больше выбор за верстальщиком остается

2021-05-27 13:03 UTC, wrgraff commented on index.html
> +      </section>
Нормально, по логике разметка хорошая, так что все ты знаешь. Только не знаешь что знаешь )
Про семантику в комментрии добавил там

2021-05-27 13:04 UTC, wrgraff commented on index.html
> +            <img src="" alt="">
Да

2021-05-27 13:05 UTC, wrgraff commented on index.html
> +      </section>
А это дискусионная тема просто.
Я считаю, что не нужен. Но другие ребята с опытом считают, что нужен.
Так как есть аргументы в обе стороны, я не настаиваю на своем варианте.

2021-05-27 13:07 UTC, wrgraff approved these changes
Ну тут полтора комментария.
Давай я приму, а ты если захочешь поправить — со следующим заданием дошли.

2021-05-27 13:07 UTC, merged

2021-05-27 13:58 UTC, kafka2020 commented on index.html
> +          <img src="" alt="Логотип" width="" height="">
Я больше не буду :)

2021-05-27 14:00 UTC, kafka2020 commented on index.html
> +            <img src="" alt="">
Ок, понял

2021-05-27 14:01 UTC, kafka2020 commented on index.html
> +      </section>
Может с накоплением знаний и у меня появиться точка зрения на этот вопрос )

2021-05-27 14:16 UTC, kafka2020 commented on index.html
> +      </div>
Изменил на <section>. На список пока не перешел - может потом передумаю