Выполняет разметку каталога
htmlacademy-htmlcss/779351-nerds-31 pull request #3
Opened 2021-05-30 22:40 UTC by kafka2020

2021-05-31 20:03 UTC, wrgraff requested changes
Так, ну для тебя это поправить вообще ничего не стоит

2021-05-31 20:03 UTC, wrgraff commented on catalog.html
> +          <button type="button">9 900 ₽</button>
На самом деле, на практике кнопки типа "Добавить в корзину" делают ссылками.
Потому что это для интернет-магазина критическая функциональность, и нужно подстраховаться и сделать так, чтобы кнопка работала без js.
Прямо в адрес ссылки может быть включен запрос с добавлением товара в корзину. При переходе на этот адрес товар добавляется в корзину и потом срабатыаает переадресация обратно, где грузится страница с уже обновленной корзиной. Будет работать с перезагрузкой страницы, но зато будет работать всегда: ссылку в html-коде сломать крайне сложно.

А потом уже поверх пишется js, который останавливает переход по ссылке и сам делает запрос, а затем обновляет состояние корзины.

2021-05-31 20:03 UTC, wrgraff commented on catalog.html
> +          <a href="#">Следующая</a>
Список — набор идентичных элементов.
А вот ссылка "следующая" точно идентична ссылке на конкретную страницу?

2021-06-01 19:57 UTC, kafka2020 commented on catalog.html
> +            <img src="https://via.placeholder.com" alt="Сайт Sedona" width="360" height="620">
Я же в следующем задании их вообще заменю на нормальный путь?

2021-06-01 20:12 UTC, kafka2020 commented on catalog.html
> +          <a href="#">Следующая</a>
да, тут разнотолки могут быть)

2021-06-02 19:10 UTC, wrgraff commented on catalog.html
> +            <img src="https://via.placeholder.com" alt="Сайт Sedona" width="360" height="620">
Наверное )

2021-06-02 19:11 UTC, wrgraff approved these changes

2021-06-02 19:11 UTC, merged