Стилизация главной страницы
htmlacademy-htmlcss/779351-nerds-31 pull request #5
Opened 2021-06-25 23:20 UTC by kafka2020

2021-06-27 03:42 UTC, wrgraff requested changes
Есть пара прям важных изменений, но в целом все неплохо

2021-06-27 03:42 UTC, wrgraff commented on index.html
> +        <div class="slide-1">
Моим студентам нельзя использовать классы типа something-1, something-2, и так далее.

Если тебе нужно стилизовать что-то по порядковому номеру, то в CSS есть такие вещи, как :first-child, :nth-child, :nth-of-type и прочие. Они придуманы специально чтобы выбирать элемент по порядку. И если их в разметке перемешать, то они все равно будут выбирать по порядку.

Если же необходимо дать стили элементу так, чтобы при перемешивании стили оставались при нём (например, иконка, которая относится непосредственно к элементу), то нужен класс.
Но только не с именем "первый", потому что оформление зависит от того, что это за элемент, а не какой он по порядку.

2021-06-27 09:09 UTC, kafka2020 commented on css/style.css
> +    url(../fonts/roboto.woff) format("woff ");
Случайно) Как избежать таких ошибок в будущем?

2021-06-27 09:13 UTC, kafka2020 commented on css/style.css
> +} */
Почему-то все картинки становятся огромными в верстке? Как так?

2021-06-27 09:14 UTC, kafka2020 commented on css/style.css
> +} */
Я же вроде задал width и height

2021-06-27 10:17 UTC, kafka2020 commented on css/style.css
> +.site-navigation a:not([href]) {
Тогда только если придумать class="active" для активного пункта меню

2021-06-27 10:47 UTC, kafka2020 commented on css/style.css
> +.feature-item {
Т.е.  класс .text лучше в одном месте только описать без использования контекстных селекторов?

2021-06-27 10:54 UTC, kafka2020 commented on css/style.css
> +  font-weight: bold;
При копировании с Figma не исправил =))
Только я не понял, почему браузер правильно жирным отобразил? Я же ну указал, что font-weight: 700; соответствует bold

2021-06-27 11:08 UTC, kafka2020 commented on css/style.css
> +  background-image:url(../img/icons/vk-icon.svg);
Я не знаю как это сделать?
Вставить как в демке svg файл в верстку?

2021-06-27 11:20 UTC, kafka2020 commented on css/style.css
> +} */
А, разобрался. Я mIn вместо mAx написал

2021-06-28 08:27 UTC, wrgraff commented on css/style.css
> +} */
Ааа, да. Я обратил внимание, что закомментил, но не посмотрел, что минимум вместо максимума )

2021-06-28 08:28 UTC, wrgraff commented on css/style.css
> +.site-navigation a:not([href]) {
Обычно так и бывает )
Но в нашем случае в принципе не критично

2021-06-28 08:29 UTC, wrgraff commented on css/style.css
> +.feature-item {
Ну, то есть у тебя должно быть по сути 2 раза написано одно и то же с разным селектором:
```css
.features .text {
  ...
}

.feature-item {
  ...
}
```

2021-06-28 08:31 UTC, wrgraff commented on css/style.css
> +  font-weight: bold;
А ему не надо указывать, он знает, что 700 это bold. Это синонимы:
100 — thin
200 — extralight
300 — light
400 — normal
500 — medium
600 — semibold
700 — bold
700 — extrabold
700 — black

2021-06-28 08:33 UTC, wrgraff commented on css/style.css
> +  background-image:url(../img/icons/vk-icon.svg);
Пока и не надо прямо финальную версию делать.
Мы в Нердсе вполне можем справиться с помощью псевдоэлемента (там зависит от того, что мы хотим от иконки). Про псевдоэлементы будет после сеток лекция

2021-06-28 08:34 UTC, wrgraff commented on css/style.css
> +    url(../fonts/roboto.woff) format("woff ");
На втором уровне линтеры будут =)

2021-06-28 08:40 UTC, wrgraff approved these changes
Я оставил еще пару комментов, но принимаю ПР, чтобы тебя не тормозить.
Все равно с этими моментами еще придется столкнуться, даже если сразу же не поправишь. И там может и очевиднее будет )

2021-06-28 08:40 UTC, wrgraff commented on css/style.css
> +    url(../fonts/roboto.woff) format("woff");
Я кстати для красоты так пишу. И свойства одно под другим читать удобно, и отступы сохраняются
```suggestion
  src:
    url(../fonts/roboto.woff2) format("woff2"),
    url(../fonts/roboto.woff) format("woff");
```

2021-06-28 08:40 UTC, wrgraff commented on index.html
> +        <div>
Ты можешь сделать им один и тот же класс для стилизации. Просто `slide`, например

2021-06-28 08:40 UTC, wrgraff commented on css/style.css
> +
Ты пока можешь оставить картинку в фоне.
Речь то шла именно о том, чтобы там была только иконка соцсети, без круга.
Потом придется вынести в псевдоэлемент эту иконку, так как она меняет прозрачность при клике, а фон меняет цвет.

2021-06-28 08:40 UTC, merged

2021-06-28 17:52 UTC, kafka2020 commented on index.html
> +        <div>
Ой, а я и хотел так сделать! Наверно, удалил, потом отвлекся и оставил как есть